In [1]:
import numpy as np

In [2]:
np.array(range(0,10))

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
np.ones((3,3), dtype='bool')

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [4]:
# get odd numbers
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
lst = []
for val in arr.tolist():
    if val % 2 != 0:
        lst.append(val)
final_arr = np.array(lst)
final_arr

array([1, 3, 5, 7, 9])

In [6]:
# other way
arr[arr % 2 == 1]

array([1, 3, 5, 7, 9])

In [7]:
# replace odd numbers with -1
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
new_arr = arr[arr % 2 == 1]
arr[new_arr] = -1
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [8]:
# other way
arr[arr%2==1] = -1

In [14]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
out = np.where(arr%2 == 1, -1, arr)
out, arr

(array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1]),
 array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]))

In [24]:
# convert 1d array to 2d array
arr = np.arange(10)
arr_2 = arr.reshape(2,-1)
arr_2

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

### Note: Reshape with -1
- Numpy automatically reshapes the size of that particular dimension from the array

In [26]:
# convert 1d array to 2d array
arr = np.arange(11)
arr_2 = arr.reshape(1,-1)
arr.shape, arr_2.shape

((11,), (1, 11))

In [30]:
# stack two array vertically
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
a.shape, b.shape
c = np.vstack((a,b))
c

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [32]:
# horizontally stack
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
c = np.concatenate([a,b], axis=1)
c

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [39]:
#custom sequence
a = np.array([1,2,3])
#op --> array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])
b = np.hstack([np.repeat(a, 3), np.tile(a,3)])
b

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [40]:
# common items btw arrays
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
c = np.intersect1d(a,b)
c

array([2, 4])

In [41]:
# remove item from one array existing in another array
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])
#op --> array([1,2,3,4])
np.setdiff1d(a,b)

array([1, 2, 3, 4])

In [45]:
# positions where elements of a and b match
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.where(a==b)

(array([1, 3, 5, 7]),)

In [50]:
# get all items between 5 and 10
a = np.array([2, 6, 1, 9, 10, 3, 27])
filt = np.where((a >= 5) & (a <= 10))
a[filt]

array([ 6,  9, 10])

In [53]:
# get the largest between 2 arrays items
def maxx(x,y):
    return np.maximum.reduce([x,y], dtype=float)

a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])
maxx(a,b)

array([6., 7., 9., 8., 9., 7., 5.])

In [54]:
# other way
def maxx(x, y):
    """Get the maximum of two items"""
    if x >= y:
        return x
    else:
        return y
    
pair_max = np.vectorize(maxx, otypes=[float])
a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])
pair_max(a,b)

array([6., 7., 9., 8., 9., 7., 5.])

In [57]:
# swap columns 1 and 2 in array
arr = np.arange(9).reshape(3,3)
print(arr)
arr[:, [1,2]] = arr[:,[2,1]]
arr


[[0 1 2]
 [3 4 5]
 [6 7 8]]


array([[0, 2, 1],
       [3, 5, 4],
       [6, 8, 7]])